### ISSUE TITLE
Temple.lib does not compile with dmd 2.066.1

### ISSUE THREAD

**Issue by ghost** [dymk/temple#13]
output log:

> C:...\func_string_gen.d(237): Error: cannot implicitly convert expression ((*cDelimPos)._expand_field_0) of type ulong to uint
> C:...\func_string_gen.d(302): Error: function temple.util.munchHeadOf (ref string a, ref string b, uint amt) is not callable using argument types (string, string, ulong)
> C:...func_string_gen.d(312): Error: cannot implicitly convert expression (delim_pos) of type immutable(ulong) to uint
> C:...\func_string_gen.d(313): Error: function temple.util.munchHeadOf (ref string a, ref string b, uint amt) is not callable using argument types (string, string, immutable(ulong))
> C:...\temple.d(60):        called from here: __temple_gen_temple_func_string("", "", "")
> TempleFunc(68): Error: argument to mixin must be a string, not (__TempleFuncStr) of type const(immutable(char)[])
> src/temple/temple.d(75): Error: u

tried with dub and or dmd from console, same output.
